sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "8"

env:
  global:
    - CI=false

services:
  - docker

install:
  - npm install

script:
  # - npm test
  - npm run build

after_success:
  - docker --version
  - docker build -f Dockerfile -t kybernetwork/yolo:$TRAVIS_COMMIT .

deploy:
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      all_branches: true
