sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "8"

env:
  global:
    - CI=false

matrix:
  include:
    - env:
        - REACT_ENV: dev
    - env:
        - REACT_ENV: staging

script:
  - echo "npm test temporarily disabled"

install:
  - npm install
  - npm run build-$REACT_ENV

after_success:
  - docker --version
  - docker build -f Dockerfile -t kybernetwork/yolo:$TRAVIS_COMMIT .

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $REACT_ENV-yolo.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: develop

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: jungle.yoloswap.com
    region: ap-southeast-1
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      branch: develop
      condition: $REACT_ENV = dev

  - provider: script
    script: bash .travis/docker_push.sh
    on:
      all_branches: true
